# Site Settings
title: Start Jekyll
email: ngpcvu.uet@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: "/sharing"
url: "http://ngocvu3010.github.io"
twitter_username: ngocvu3010
github_username:  ngocvu3010
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
